# Generated by Django 3.2.8 on 2021-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Actor name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Movie title')),
                ('genre', models.CharField(max_length=30, verbose_name='Movie genre')),
                ('raiting', models.IntegerField(default=0, verbose_name='Movie raiting')),
                ('actors', models.ManyToManyField(to='main.Actor')),
            ],
        ),
    ]
