# Generated by Django 3.2.8 on 2021-11-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='raiting',
            field=models.IntegerField(default=0, verbose_name='Movie raiting'),
        ),
    ]
