version: "3.2"
services:
  web: &web
    image: django_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - rabbitmq
      - celery
      - celery-beat
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  celery:
    <<: *web
    command: celery -A app worker -l info
    ports: []
    environment:
      - DEBUG=1
    depends_on:
      - db
      - rabbitmq
  celery-beat:
    <<: *web
    command: celery -A app beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=1
    ports: []
    depends_on:
      - db
      - rabbitmq
  flower:
    <<: *web
    command: celery -A app flower --broker=amqp://guest:guest@rabbitmq:5672// --port=5566
    environment:
      - DEBUG=1
    ports:
      - 5566:5566
    depends_on:
      - db
      - rabbitmq
      - celery
      - celery-beat